### ISSUE TITLE
sometimes access fails and I have to re-signin

### ISSUE THREAD

**Issue by stevesouders** [elsigh/chartcomposer#59]
I'm going along fine (Chrome macbook) and then I click on a song (in this case Amazing Grace but it also happens to other songs) and the dancing notes loader goes indefinitely. In the console there's this error:
```
Uncaught (in promise) {error: "{"error_summary": "shared_link_is_directory/", "error": {".tag": "shared_link_is_directory"}}", response: Response, status: 409}
Promise.then (async)
n.setSongId @ index.js:1
t @ index.js:1
p @ main.js:1
invokeGuardedCallback @ main.js:1
invokeGuardedCallbackAndCatchFirstError @ main.js:1
N @ main.js:1
I @ main.js:1
A @ main.js:1
j @ main.js:1
F @ main.js:1
U @ main.js:1
kn @ main.js:1
batchedUpdates @ main.js:1
We @ main.js:1
jn @ main.js:1
interactiveUpdates @ main.js:1
Pn @ main.js:1
a @ main.js:1
```
If I sign out and sign back in (Dropbox oath) it works.

This happens 1-2 times per day.

**Comment by stevesouders** [comment]
If nothing else it'd be nice to detect the error and get out of the "frozen" state of a gray background and infinite dancing notes.

**Comment by stevesouders** [comment]
Not sure if this helps: I had one song that would never load. In console I saw the "NOT SYNCING CUZ DIRTY" message, so I deleted the song from Dropbox, reloaded CC a few times, then copied the song back into my folder with a different name and reloaded CC and it worked. Then I renamed it back to the original name and reloaded CC and that also worked. 

I wonder if somehow when we autosave it gets "dirty" and then we can't load it?

**Comment by elsigh** [comment]
I think the way I did 7d5c23fcfc77ff832a0f1472fd296da88ece299a is why the loading spinner is stuck, but I don't believe that's the core of the issue here - and reading https://www.dropboxforum.com/t5/API-Support-Feedback/API-v2-access-token-validity/td-p/215123 makes me think this isn't a token expiration, but rather a state-setting bug in chartcomposer's code.

I can repro the issue, but a refresh fixes things for me.

I notice that the `.tag` property is missing in the `song` object on API requests when this happens.. investigating

**Comment by elsigh** [comment]
aha, lame-city - the dropbox API's save response object doesn't include the `.tag` property in its responses, and so it's getting lost after the first save.
